// ADDRESSES
export const GET_ADDRESSES = 'GET_ADDRESSES'

// BRANCHES
export const GET_BRANCHES = 'GET_BRANCHES'

// BRANDS
export const GET_BRANDS = 'GET_BRANDS'

// CART
export const UPDATE_CART = 'UPDATE_CART'
export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const CLEAR_CART = 'CLEAR_CART'
export const UPDATE_REMOTE_CART = 'UPDATE_REMOTE_CART'

//
export const ADD_BUY_NOW = 'ADD_BUY_NOW'
export const REMOVE_BUY_NOW = 'REMOVE_BUY_NOW'
// CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES'

// COUNTRIES
export const GET_COUNTRIES = 'GET_COUNTRIES'

// ORDERS
export const GET_ORDERS = 'GET_ORDERS'
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS'
export const SET_ORDER_ITEMS = 'SET_ORDER_ITEMS'
export const SET_ORDER_ADDRESS = 'SET_ORDER_ADDRESS'
export const SET_ORDER_PAYMENT = 'SET_ORDER_PAYMENT'
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'
export const CLEAR_CREATED_ORDER = 'CLEAR_CREATED_ORDER'
export const ADD_ORDERS_FILTER = 'ADD_ORDERS_FILTER'
export const CLEAR_ORDERS_FILTER = 'CLEAR_ORDERS_FILTER'
// PAYMENTS
export const GET_PAYMENTS = 'GET_PAYMENTS'

// PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS'
export const ADD_PRODUCTS_FILTER = 'ADD_PRODUCTS_FILTER'
export const SET_PRODUCTS_SORTING = 'SET_PRODUCTS_SORTING'
export const CLEAR_PRODUCTS_FILTER = 'CLEAR_PRODUCTS_FILTER'
export const CREATE_NEW_PRODUCT = 'CREATE_NEW_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'

// REVIEWS
export const GET_USER_REVIEWS = 'GET_USER_REVIEWS'
export const CREATE_REVIEW = 'CREATE_REVIEW'
// SYSTEM
export const SET_TOAST = 'SET_TOAST'
export const SET_USERS_TAB = 'SET_USERS_TAB'
export const SET_ADMINS_TAB = 'SET_ADMINS_TAB'

// USERS
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const GET_USERS = 'GET_USERS'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const CHANGE_USER_ROLE = 'CHANGE_USER_ROLES'
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
export const FORCE_PASSWORD_RESET = 'FORCE_PASSWORD_RESET'
// WISHLIST
export const GET_WISHLIST = 'GET_WISHLIST'

// FUTURE REMINDER

export const CREATE_NEWSLETTER = 'CREATE_NEWSLETTER'
export const UPDATE_NEWSLETTER = 'UPDATE_NEWSLETTER'
export const REMOVE_NEWSLETTER = 'REMOVE_NEWSLETTER'
export const CREATE_RULE = 'CREATE_RULES'
export const UPDATE_RULE = 'UPDATE_RULE'
export const REMOVE_RULE = 'REMOVE_RULE'

// INVENTORY

export const GET_ALL_INVENTORY = 'GET_ALL_INVENTORY'
export const GET_ALL_STOCK_BRANCH = 'GET_ALL_STOCK_BRANCH'
export const GET_PRODUCT_EXIST = 'GET_PRODUCT_EXIST'
export const GET_STOCK_PRODUCT_BRANCH = 'GET_STOCK_PRODUCT_BRANCH'
export const POST_PRODUCT_INVENTORY = 'POST_PRODUCT_INVENTORY'
export const PUT_PRODUCT_INVENTORY = 'PUT_PRODUCT_INVENTORY'
export const CLEAN_INVENTORY = 'CLEAN_INVENTORY'
