export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS'
export const ADD_FILTER_PARAM = 'ADD_FILTER_PARAM'
export const SET_ORDER_TYPE = 'SET_ORDER_TYPE'

// CART
export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS'
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const REMOVE_ALL_CART_PRODUCTS = 'REMOVE_ALL_CART_PRODUCTS'
